trigger:
  - master

name: "Paymentsense Coding Challenge"

variables:
  projectName: "Paymentsense.Coding.Challenge"

stages:
  - stage: "Build"
    displayName: "Build and Test"
    jobs:
      - job: BuildBackend
        displayName: "Build and Test Backend"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: "jobs/build-backend.yml"
            parameters:
              workingDirectory: paymentsense-coding-challenge-api
              buildPlatform: "Any CPU"
              buildConfiguration: "Release"
      - job: BuildFrontend
        displayName: "Build And Test Frontend"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - template: "jobs/build-frontend.yml"
            parameters:
              workingDirectory: paymentsense-coding-challenge-website
