# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: "Build"
    displayName: "Build and Test"
    jobs:
      - job:
        displayName: 'Build and Test Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: 'jobs/build-frontend.yml'
      - job:
        displayName: 'Build and Test Backend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: 'jobs/build-backend.yml'
